name: scottssite
favicon: null
layout_spectrum: 0.8313088989816606
typography_spectrum: 0.3817761321552098
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6302026365883648
  lightness: 0.3944697503466159
  saturation: 0.19623043341562152
  rhythmicContrast: 0.09986845077946782
purpose: []
